# Generated by Django 2.2.4 on 2019-10-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_news_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Live Files', max_length=50)),
                ('audio_url', models.URLField()),
                ('video_url', models.TextField(blank=True)),
                ('is_live', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Live_radio',
        ),
    ]
