# Generated by Django 2.2.4 on 2019-10-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20191015_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live_file',
            name='video_url',
            field=models.TextField(blank=True),
        ),
    ]
