# Generated by Django 2.2.4 on 2019-10-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20191015_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live_file',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
